# Generated by Django 3.2.5 on 2021-07-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='thumbnail',
            field=models.ImageField(default='images/thumbnail/user_image.jpg', upload_to='images/thumbnail/', verbose_name='サムネイル'),
        ),
    ]
